### ISSUE TITLE
Add correct velocity value to StationDataContainer, OriginatingVehicleContainer, speed

### ISSUE THREAD

**Issue by yuasabe** [tlab-wide/AutowareV2X#9]
StationDataContainer, OriginatingVehicleContainer, speed in the CPMs are currently set to 0. Add correct value from Autoware.

The vehicle velocity in Autoware is tracked in the `/vehicle/status/velocity_status` topic of type `autoware_auto_vehicle_msgs/msg/VelocityReport`. Example below. The `longitudinal_velocity` is what we want in meters per second.

```
---
header:
  stamp:
    sec: 1652955962
    nanosec: 756808121
  frame_id: base_link
longitudinal_velocity: 0.0
lateral_velocity: 0.0
heading_rate: -0.0
---
```
